# Install Docker section
install_docker: yes 

# Create users section
create_users: yes

## A user is composed of a name, password, and groups
## To be able to use sudo, a user must be in the sudo group
## To be able to use docker, a user must be in the docker group
users: 
  - name: user1
    password: password1
    groups: 
      - sudo
      - docker
  - name: user2
    password: password2
    groups: 
      - sudo
      - docker
  - name: user3
    password: password3
    groups: 
      - sudo
      - docker