- name: Create output folder
  file:
    path: "./{{ create_users.private_key_dest }}/{{ user.name }}"
    state: directory
    mode: 0755
  become: false
  delegate_to: localhost

- name: Copy private key to output folder
  fetch:
    flat: yes
    src: "{{ user.ssh_key_file }}"
    dest: "./{{ create_users.private_key_dest }}/{{ user.name }}/"
    mode: 0400

- name: Add public key to authorized key file
  lineinfile:
    path: "{{ user.home }}/.ssh/authorized_keys"
    line: "{{ user.ssh_public_key }}"
    create: yes
    mode: 0644

