- name: Remove hosts from known_hosts on localhost
  hosts: localhost
  gather_facts: false  # We don't need facts for this task

  tasks:
    - name: Remove hosts from known_hosts
      known_hosts:
        path: "~/.ssh/known_hosts"
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ groups['vms'] | map('extract', hostvars, 'ansible_host') | list }}"

- hosts: vms 
  become: true    

  pre_tasks:
    - debug:
        msg: 'Beginning server configuration on {{ inventory_hostname }}.'

  roles:
    # Archive for exemple
    # - role: roles/docker_install
    #   when: install_docker.enable is true

    - role: geerlingguy.docker 
      when: common.install_docker is true

    - role: geerlingguy.git
      when: common.install_git is true

    - role: roles/create_users
      when: create_users.enable is true
    
    - role: roles/citation_api_config
      vars:
        host_ip: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      when: 
        - citation_api_config.enable is true
        - inventory_hostname == citation_api_config.target_host

  post_tasks:
    - debug:
        msg: 'Server {{ inventory_hostname }} has been configured.'